//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.UAM.Inscripciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASPIRANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASPIRANTE()
        {
            this.INSCRIPCION_ASPIRANTE = new HashSet<INSCRIPCION_ASPIRANTE>();
        }
    
        public int ID { get; set; }
        public string PRIMER_NOMBRE { get; set; }
        public string SEGUNDO_NOMBRE { get; set; }
        public string PRIMER_APELLIDO { get; set; }
        public string SEGUNDO_APELLIDO { get; set; }
        public Nullable<System.DateTime> NACIMIENTO { get; set; }
        public Nullable<int> ID_GENERO { get; set; }
        public Nullable<int> ID_CIUDAD_NACIMIENTO { get; set; }
        public Nullable<int> ID_GRUPO_SANGUINEO { get; set; }
        public string IDENTIFICACION { get; set; }
        public Nullable<int> ID_CIUDAD_EXPEDICION { get; set; }
        public Nullable<int> ID_ESTADO_CIVIL { get; set; }
        public Nullable<int> ID_TIPO_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> FECHA_EXPEDICION { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual CIUDAD CIUDAD1 { get; set; }
        public virtual ESTADO_CIVIL ESTADO_CIVIL { get; set; }
        public virtual GENERO GENERO { get; set; }
        public virtual GRUPO_SANGUINEO GRUPO_SANGUINEO { get; set; }
        public virtual TIPO_DOCUMENTO TIPO_DOCUMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSCRIPCION_ASPIRANTE> INSCRIPCION_ASPIRANTE { get; set; }
    }
}
