//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.UAM.Inscripciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSCRIPCION_ASPIRANTE
    {
        public int ID { get; set; }
        public Nullable<int> ID_ASPIRANTE { get; set; }
        public Nullable<int> ID_TIPO_ASPIRANTE { get; set; }
        public Nullable<int> ID_MODALIDAD { get; set; }
        public Nullable<int> ID_PROGRAMA_ACADEMICO { get; set; }
        public Nullable<int> ID_SEDE { get; set; }
        public Nullable<int> ID_PERIODO_ACADEMICO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ASPIRANTE ASPIRANTE { get; set; }
        public virtual MODALIDAD_ESTUDIO MODALIDAD_ESTUDIO { get; set; }
        public virtual PERIODO_ACADEMICO PERIODO_ACADEMICO { get; set; }
        public virtual PROGRAMA_ACADEMICO PROGRAMA_ACADEMICO { get; set; }
        public virtual SEDE SEDE { get; set; }
        public virtual TIPO_ASPIRANTE TIPO_ASPIRANTE { get; set; }
    }
}
