//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.UAM.Inscripciones.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PRUEBA_UAMEntities : DbContext
    {
        public PRUEBA_UAMEntities()
            : base("name=PRUEBA_UAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASPIRANTE> ASPIRANTE { get; set; }
        public virtual DbSet<CIUDAD> CIUDAD { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<ESTADO_CIVIL> ESTADO_CIVIL { get; set; }
        public virtual DbSet<GENERO> GENERO { get; set; }
        public virtual DbSet<GRUPO_SANGUINEO> GRUPO_SANGUINEO { get; set; }
        public virtual DbSet<INSCRIPCION_ASPIRANTE> INSCRIPCION_ASPIRANTE { get; set; }
        public virtual DbSet<MODALIDAD_ESTUDIO> MODALIDAD_ESTUDIO { get; set; }
        public virtual DbSet<PAIS> PAIS { get; set; }
        public virtual DbSet<PERIODO_ACADEMICO> PERIODO_ACADEMICO { get; set; }
        public virtual DbSet<PROGRAMA_ACADEMICO> PROGRAMA_ACADEMICO { get; set; }
        public virtual DbSet<SEDE> SEDE { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPO_ASPIRANTE> TIPO_ASPIRANTE { get; set; }
        public virtual DbSet<TIPO_DOCUMENTO> TIPO_DOCUMENTO { get; set; }
    
        public virtual ObjectResult<ASPIRANTES_INSCRITOS_Result> ASPIRANTES_INSCRITOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ASPIRANTES_INSCRITOS_Result>("ASPIRANTES_INSCRITOS");
        }
    }
}
